version: "3.9"

##########################
#      ENVIRONMENT       #
##########################
# .env 
# POSTGRES_PASSWORD=password123
# LLM_MODEL=google/flan-t5-small

##########################
#        SERVICES        #
##########################
services:
  # -------------------------------------------------
  # PostgreSQL 15
  # -------------------------------------------------
  db:
    image: postgres:15
    container_name: ai-agent-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mydb
    
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=trust"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d  
    ports:
      - "5432:5432"    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # -------------------------------------------------
  # FastAPI + LangGraph Agent
  # -------------------------------------------------
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-agent-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
     
      DATABASE_URL: "postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@db:5432/mydb"
      
      LLM_MODEL: ${LLM_MODEL}
    ports:
      - "8000:8000"     # Swagger UI → http://localhost:8000/docs
    command: >
      uvicorn src.main:app
      --host 0.0.0.0
      --port 8000
      --log-level info
    restart: unless-stopped

##########################
#        NETWORKS        #
##########################

#
# networks:
#   default:
#     name: ai-agent-net
